import { ALL_TEMPLATES, generateScenario } from '../src/engine.js';
import { FAMILIES } from '../src/catalog.js';
import { writeFile } from 'node:fs/promises';
let text=`# Scenario catalog\n\n${ALL_TEMPLATES.length} authored templates. Generated by \`node scripts/catalog.mjs\`. The sample seed is \`catalog-example\`; parameters vary within compatible templates.\n\n`;
for(const family of FAMILIES){
  const templates=ALL_TEMPLATES.filter(t=>t.family===family.id);
  text+=`## ${family.name} (${templates.length})\n\n${family.question}\n\n`;
  for(const t of templates){const s=generateScenario('catalog-example',{templateId:t.id});text+=`### ${s.title}\n\n- ID: \`${s.id}\`\n- Lens: ${s.lens}\n- Type: ${t.stage===undefined?'core exploration template':`narrative stage ${t.stage+1}`}\n- Setup: ${s.setup}\n- Original route: ${s.main}\n- Intervention route: ${s.side}\n\n`;}
}
await writeFile('docs/CATALOG.md',text);console.log(`Documented ${ALL_TEMPLATES.length} templates.`);
