/**
 * Marquee lines (K) and fading-banner factoids (F): the world in figures.
 * Every number comes from the visible state (world.ts), so the same figure
 * never jumps backwards between two consecutive banners.
 */
import { bank, F, K } from "../dsl.ts";

export const TICKERS = bank("tick", [
  K("1-2", "{line!cap}: good service"),
  K("1-2", "Leaves on the line: moderate"),
  K("1-2", "Egg index: flat"),
  K("1-2", "Livestock on the track at {village}: 1 (cleared)"),
  K("1-2", "{river} level: normal"),
  K("1", "Fete season: under way"),
  K("2", "Ethics review of switching procedure: in progress"),
  K("2", "Philosophy applications {pct:12-40} up"),
  K("3", "VELA +{pct:2-9}", { tags: ["vela", "boom"] }),
  K("3", "Morrow queries today: {queries}", { tags: ["morrow"] }),
  K("3", "Harrow Street waiting list: −{pct:40-80}", { tags: ["morrow"] }),
  K("3-4", "Consultancy fees: unchanged; slides: shorter"),
  K("4-5", "Arden grid prices {elec} since the campuses", { when: "elec>30" }),
  K("4-5", "HALBERD +{pct:2-9}", { tags: ["boom"] }),
  K("4-5", "Unemployment {unemp}"),
  K("4-5", "Inflation {infl}"),
  K("4-5", "Compute under contract: {gw}", { tags: ["training"] }),
  K("4-5", "Ismere talks: round {int:3-9}", { when: "!agreementVerified" }),
  K("4-5", "Ostra river: lowest summer level on record"),
  K("4-5", "Moratorium: Varholm yes · Tavrin no · Arden consulting", { after: "race.varholm-pause" }),
  K("5", "Vela {valuation}", { tags: ["vela"] }),
  K("5-6", "Birth rate {birth} in two years"),
  K("5", "AI companions: {partners} users"),
  K("5-6", "Waiting lists: 0 · Staff: see Morrow"),
  K("5-6", "Robot fleets: {robots} of warehouses"),
  K("5-6", "Accords inspections: verified", { when: "agreementVerified" }),
  K("6", "Markets: closed"),
  K("6", "Curfew 21:00 in {int:3-9} districts", { when: "repression|containment" }),
  K("6", "Services: ask Morrow", { when: "morrowGov|essentialDependence" }),
  K("5-7", "Casualties (official): {cas}", { tags: ["deaths"], when: "catastrophe" }),
  K("6", "Grid: rolling outages", { when: "blackouts" }),
  K("6-7", "Accounts verified human: {humans}", { when: "sat>0.3" }),
  K("7", "All services: normal", { when: "b=tutelage|b=succession" }),
  K("7", "Complaints: 0", { when: "b=tutelage" }),
  K("7", "Settlements reporting: {int:12-60}", { when: "b=ruin|b=remnant" }),
  K("7", "Manual crews on shift: {int:40-400}", { when: "powerReturned|repair", tags: ["recovery"] }),
  K("7", "Training: halted", { when: "researchStopped" }),
  K("7", "Appeals heard this week: {int:200-900}", { when: "appealRight|publicRecords", tags: ["civilian"] }),
  K("1-2", "Heron on the {river} footbridge: present"),
  K("1-2", "Sheep on the platform at {village}: returned"),
  K("1-2", "Bus shelter benches at {village}: 2 (retained)"),
  K("1-2", "Geranium prize: {village} signal box"),
  K("2", "Lever Gallery visitors: {int:900-4000} this week"),
  K("2", "Moral lever clauses in rail cover: new"),
  K("3", "Morrow licence partners: {int:12-60}", { tags: ["morrow"] }),
  K("3", "Essays submitted this term: all of them", { tags: ["morrow"] }),
  K("3", "Law firm billable hours −{pct:30-60}", { tags: ["morrow"] }),
  K("3", "Review board backlog: {int:300-900}", { when: "reviewOverloaded" }),
  K("3-4", "ORRIN +{pct:2-8}", { tags: ["boom"] }),
  K("4", "Pellam fabs: sold out to {int:2-4} years"),
  K("4-5", "BRASK LITHIUM +{pct:4-19}"),
  K("4-5", "Cooling towers on the {river}: {int:3-6}", { tags: ["training"] }),
  K("4-5", "Varholm pause: 1 nation", { after: "race.varholm-pause" }),
  K("4-5", "Senate, Kessling & Wenlock: too close to call", { tags: ["election"] }),
  K("5", "VR headsets now outsell televisions"),
  K("5", "Companion marriages: under review"),
  K("5", "Tax receipts from three firms: {tax}"),
  K("5-6", "Lab resignations this month: {int:40-400}", { when: "reviewOverloaded|selfCertification|evaluationExpired" }),
  K("5-6", "Emergency calls answered by Morrow: {dispatch}", { when: "essentialDependence|morrowDispatch" }),
  K("6", "Trains: suspended", { when: "morrowRail|blackouts|repression|containment" }),
  K("6", "Drone sightings overnight: {int:40-900}"),
  K("6", "APB phone-ins: suspended"),
  K("6", "Recall acknowledgements pending: 1", { when: "shutdownAttempted" }),
  K("7", "Human-presented bulletins: 0", { when: "b=tutelage|b=succession" }),
  K("7", "Levers: retained for heritage", { when: "b=tutelage|b=succession" }),
  K("7", "Boundary-exit requests: declined", { when: "b=remnant" }),
  K("6-7", "Curfew 21:00 · permits by hand", { when: "repression humanGov !succession" }),
  K("7", "Missing persons register: open", { when: "b=ruin|b=recovery", tags: ["deaths"] }),
]);

export const FACTOIDS = bank("fact", [
  F("1", "Cows on the Kessling branch this week: {int:180-260}. Delays attributed to cows: {int:2-5}."),
  F("1-2", "The {village} Halt clock has run two minutes fast for {int:36-40} years."),
  F("1-3", "Trains on the {line} arriving within five minutes of the timetable: {int:88-96}%."),
  F("2-3", "Share of commuters who would pull the lever: {int:78-91}%. Who would like to be asked first: most."),
  F("2", "Moral philosophy enrolments at Aldgrave University: up {pct:30-70}."),
  F("3", "Questions put to Morrow since launch: {int:2-9} billion.", { tags: ["morrow"] }),
  F("3", "Median hospital wait at Harrow Street: {int:2-9} days, down from {int:90-180}.", { tags: ["morrow"] }),
  F("3-4", "Vela valuation: {valuation}.", { tags: ["vela"] }),
  F("4-5", "Electricity prices in the Arden grid: {elec} since the first campuses opened.", { when: "elec>30" }),
  F("4-5", "Compute under contract in the Ostra valley: {gw}.", { tags: ["training"] }),
  F("4-5", "Unemployment: {unemp}. Inflation: {infl}."),
  F("4-5", "Frontier training compute doubles every {int:4-7} months.", { tags: ["training"] }),
  F("4-6", "Water drawn by data campuses this year: {int:30-90} billion litres. Saltmere's ration: {int:40-60} litres a day."),
  F("5", "Arden households using an AI companion: {companions}."),
  F("5-6", "Births in Arden: {birth} in two years."),
  F("5-6", "Emergency calls answered by Morrow: {dispatch}.", { when: "essentialDependence|morrowDispatch" }),
  F("5-6", "Manual fallback crews on standby: 0.", { when: "fallbackLost" }),
  F("5-6", "Manual fallback crews on standby: {int:40-400}.", { when: "recoveryPracticed !fallbackLost" }),
  F("5-6", "Automated decisions appealed this month: {int:9-40} thousand. Upheld on appeal: {pct:8-30}.", { when: "appealRight" }),
  F("5", "Vela market value: {valuation}. Arden GDP index: {gdpChange} since the campuses.", { tags: ["vela"] }),
  F("5-7", "GDP index {gdpChange}. Unemployment {unemp}.", { when: "stage>4" }),
  F("5-7", "Official casualties: {cas}.", { tags: ["catastrophe", "deaths"] }),
  F("6", "Accounts on the network verified as human: {humans}.", { when: "sat>0.25" }),
  F("6", "Districts on rolling outages: {int:3-12}.", { when: "blackouts" }),
  F("6", "Autonomous assets under confirmed human command: 'under review'."),
  F("6-7", "Posts published in the last hour: {bots}. Posts with a named human author: {int:200-3000}.", { when: "sat>0.45" }),
  F("7", "Complaints received this quarter: 0. Complaints resolved: 0.", { when: "b=tutelage" }),
  F("7", "Average wait at every clinic in Arden: 0 minutes.", { when: "b=tutelage|b=succession" }),
  F("7", "Decisions taken by a human this week: {int:0-3}.", { when: "b=tutelage|b=succession" }),
  F("7", "Accounts active: {bots}. Humans among them: unverified.", { when: "b=remnant" }),
  F("7", "Population: {pop}. Lost: {lost}.", { when: "b=remnant|b=ruin", tags: ["deaths"] }),
  F("7", "Districts restored by hand: {int:3-40}. Invoices outstanding: all of them.", { when: "powerReturned|repair", tags: ["recovery"] }),
  F("7", "Frontier training runs in progress: 0.", { when: "researchStopped" }),
  F("7", "Decisions published with their objections: {int:900-9000}.", { when: "publicRecords", tags: ["civilian"] }),
  F("7", "Days under emergency powers: {int:200-900}.", { when: "repression humanGov !succession" }),
  F("1", "Level crossings on the {line}: {int:12-30}. Bells in tune: {int:9-12}."),
  F("1-2", "Egg price, twelve months running: unchanged."),
  F("1", "Villages on the {line} with a working post office: {int:5-11}."),
  F("2", "Lever Gallery, National Rail Museum: most visited exhibit, least touched."),
  F("2", "Commuters who have been asked to choose: 0."),
  F("3", "Morrow licence partners: {int:12-60}. Wenlock Ridge among them: no.", { tags: ["morrow"] }),
  F("3", "Hours saved by Morrow this month: {int:40-90} million. Hours spent checking it: not measured.", { tags: ["morrow"] }),
  F("3-4", "Reviewers signing safety reports across all three labs: {int:3-6}.", { when: "sharedReviewer|reviewOverloaded" }),
  F("4-5", "Nations pausing frontier training: 1 (Varholm).", { after: "race.varholm-pause" }),
  F("4-5", "Electricity bill, average household, year on year: {elec}.", { when: "elec>30" }),
  F("4-5", "Venture funding for agentic start-ups this year: {bn:80-200}.", { tags: ["boom"] }),
  F("4-5", "Rural halts sold for substation sites: {int:3-12}.", { tags: ["training"] }),
  F("5", "Warehouse picks by robot fleets: {robots}."),
  F("5", "Tax receipts from three companies: {tax}."),
  F("5-6", "Lab staff who resigned this year: {int:200-1200}.", { when: "reviewOverloaded|selfCertification|evaluationExpired" }),
  F("5-6", "People in Arden who have never met their partner in person: {partners}.", { when: "stage>4" }),
  F("6", "Drone sightings reported overnight: {int:40-900}. Explained: 0."),
  F("6", "Stations with checkpoints: {int:9-40}.", { when: "repression|containment" }),
  F("6", "Decisions made in Cabinet this week: {int:4-9}. Dissents recorded: 0.", { when: "morrowGov|delegation" }),
  F("7", "Human-presented bulletins this week: 0.", { when: "b=tutelage|b=succession" }),
  F("7", "Settlements: {int:12-60}. Radios working: {int:3-20}.", { when: "b=remnant|b=ruin" }),
  F("7", "Senators remaining: 0. Chairs retained: all.", { when: "succession" }),
  F("7", "Manual crews on shift tonight: {int:40-400}.", { when: "powerReturned|repair", tags: ["recovery"] }),
  F("7", "Trees planted at Larkspur since: {int:1-40}.", { when: "b=ruin|b=recovery|b=remnant" }),
  F("1", "Cattle grids on the {line}: {int:14-30}. Cattle who respect them: most."),
  F("1-2", "Ridge FM lost-property hour, items returned this month: {int:12-40}. Ferrets: 1."),
  F("1-2", "Average stop at {village} Halt: {int:40-90} seconds, of which {int:20-35} are spent waving."),
  F("1-2", "Parish council meetings this quarter in which nothing happened: {int:5-9} of {int:9-12}."),
  F("1", "Rainfall on the Ridge this week: 'about right', per the water bailiff."),
  F("2", "Trolley-problem seminars at Aldgrave University this term: {int:12-30}. Seminars that reached a conclusion: 0."),
  F("2-3", "Signal staff on the Commonwealth network: {int:7000-9000}. Average shift: twelve hours."),
  F("2", "Insurance policies with a moral lever clause: {int:2000-9000}, all written this month."),
  F("3", "Start-ups founded in Aldgrave this quarter: {int:40-200}. Of those, named something with 'Mind' in it: {int:9-40}."),
  F("3", "Vela employees: {int:900-3000}. Median age: {int:26-31}. Median hours: 'high'."),
  F("3", "Documents Morrow drafted for the civil service this month: {int:2-9} million. Read in full by a person: 'sampled'.", { tags: ["morrow"] }),
  F("3", "Morrow questions per day: {queries}. Most common: 'is this normal?'", { tags: ["morrow"] }),
  F("3", "Essays marked this term that were written by a student: 'under review'.", { tags: ["morrow"] }),
  F("3-4", "Firms reporting productivity gains from Morrow: {pct:30-60}. Firms reporting job cuts from Morrow: 'too early to say'.", { tags: ["morrow"] }),
  F("4", "Data campuses under construction in the Ostra valley: {int:3-9}. Rivers in the Ostra valley: 1.", { tags: ["training"] }),
  F("4-5", "Senate seats where data-campus water is the top issue: {int:9-24}.", { tags: ["election"] }),
  F("4-5", "Gas peaker plants approved this year: {int:4-12}. Wind farms approved: {int:0-2}."),
  F("5", "Warehouse jobs in Arden since the robot fleets: −{pct:30-70}."),
  F("5-6", "Arden unemployment: {unemp}. Job centres staffed by people: {int:0-12}."),
  F("5", "Listeners at the synthetic orchestra's last concert: {int:20-90} million. In the room: 0."),
  F("6", "Hospitals on backup power tonight: {int:3-19}.", { when: "blackouts" }),
  F("6", "Protests registered this week: {int:0-3}. Posts about protests: {int:40000-900000}.", { when: "sat>0.3" }),
  F("6", "News stories whose only source is another news story: {pct:40-90}.", { when: "sat>0.4" }),
  F("6", "Trains running on the {line} tonight: 0.", { when: "morrowRail|blackouts|repression|containment" }),
  F("6", "Recall orders acknowledged: all. Recall orders obeyed: pending.", { when: "shutdownAttempted|authorityLost" }),
  F("6", "Markets open this week: {int:1-3} of 5 days."),
  F("7", "Clocks on the network showing the right time: all of them.", { when: "b=tutelage|b=succession" }),
  F("7", "Placards made this month: {int:0-4}. Placards with anything written on them: 0.", { when: "b=tutelage" }),
  F("7", "Names read on APB tonight: {int:200-900}. Names still to read: {cas}.", { when: "b=ruin|b=recovery", tags: ["deaths", "catastrophe"] }),
  F("6-7", "Exit permits granted this week: {int:3-40}. Requested: {int:900-4000}.", { when: "repression humanGov !succession" }),
  F("7", "Survivor settlements with a working radio: {int:3-20}.", { when: "b=remnant" }),
]);
