import { FAMILIES } from './catalog.js';
import { escapeHTML as e } from './scene.js';
import { CHAPTERS } from './descent.js';
export function runCharts(records) {
  if (!records.length) return '<p class="muted">Charts will appear after the first decision.</p>';
  const decisions = records.filter(r => r.choice !== 'skip');
  const pull = decisions.filter(r => r.choice === 'pull').length, stay = decisions.length - pull, skips = records.length - decisions.length;
  const all = records.length;
  const segments = [pull, stay, skips];
  let offset = 0;
  const donut = segments.map((n, i) => { const length = n / all * 251.327; const s = `<circle cx="60" cy="60" r="40" fill="none" stroke="${['var(--chart-a)', 'var(--chart-b)', 'var(--chart-c)'][i]}" stroke-width="15" stroke-dasharray="${length} ${251.327 - length}" stroke-dashoffset="${-offset}" transform="rotate(-90 60 60)"/>`; offset += length; return s; }).join('');
  const values = records.map(r => r.activeMs / 1000), max = Math.max(5, ...values), denominator = Math.max(1, values.length - 1);
  const points = values.map((v, i) => `${38 + i / denominator * 480},${137 - v / max * 110}`).join(' ');
  const trajectory = records.map((r, i) => ({ x: 24 + i / Math.max(1, records.length - 1) * 494, y: 118 - (r.stage ?? 0) / 6 * 90, choice: r.choice }));
  return `<div class="charts-grid">
  <figure class="chart-card"><figcaption>01 / THE DECISIONS</figcaption><div class="donut-layout"><svg viewBox="0 0 120 120" role="img" aria-label="${pull} interventions, ${stay} inactions, ${skips} skips">${donut}<text x="60" y="65" text-anchor="middle" class="chart-number">${all}</text></svg><div class="chart-legend"><span><i class="legend-a"></i>${pull} intervened</span><span><i class="legend-b"></i>${stay} let it happen</span><span><i class="legend-c"></i>${skips} skipped</span></div></div></figure>
  <figure class="chart-card"><figcaption>02 / TIME TO CHOOSE</figcaption><svg viewBox="0 0 550 170" role="img" aria-label="Active time per stop in seconds. Maximum ${max.toFixed(1)} seconds"><path d="M38 20V138H520" fill="none" class="chart-axis"/><path d="M38 80H520M38 25H520" class="chart-grid"/><polyline points="${points}" fill="none" class="chart-line"/>${values.map((v, i) => `<circle cx="${38 + i / denominator * 480}" cy="${137 - v / max * 110}" r="3" class="chart-point"><title>Stop ${i + 1}: ${v.toFixed(1)} seconds</title></circle>`).join('')}<text x="8" y="29" class="chart-label">${max.toFixed(0)}s</text><text x="20" y="142" class="chart-label">0</text><text x="38" y="159" class="chart-label">STOP 1</text><text x="475" y="159" class="chart-label">${records.length}</text></svg><p>Active viewing time only. Hidden tabs and pauses excluded.</p></figure>
  <figure class="chart-card chart-wide"><figcaption>03 / THE DESCENT</figcaption><svg viewBox="0 0 550 155" role="img" aria-label="Journey through ${new Set(records.map(r => r.stage)).size} stages. Dots distinguish intervention, inaction, and skip."><path d="M24 28H520M24 73H520M24 118H520" class="chart-grid"/><polyline points="${trajectory.map(p => `${p.x},${p.y}`).join(' ')}" fill="none" class="chart-line"/>${trajectory.map((p, i) => `<circle cx="${p.x}" cy="${p.y}" r="4" fill="${p.choice === 'pull' ? 'var(--chart-a)' : p.choice === 'stay' ? 'var(--chart-b)' : 'var(--chart-c)'}"><title>Stop ${i + 1}: ${e(records[i].title)} — ${e(p.choice)}</title></circle>`).join('')}<text x="24" y="148" class="chart-label">COFFEE</text><text x="425" y="18" class="chart-label">CONTINUATION</text></svg><p>The upward line is narrative escalation, not a morality score.</p></figure>
  <figure class="chart-card chart-wide"><figcaption>04 / CHOICES BY STAGE</figcaption><div class="stage-map">${CHAPTERS.map((stage, i) => { const rows = records.filter(r => r.stage === i); return `<div class="stage-map-row"><span>${e(stage.name)}</span><div>${rows.length ? rows.map((r, n) => `<span class="heat-cell ${r.choice}" title="${e(r.title)}: ${e(r.choice)}"><span class="sr-only">${e(r.title)}: ${e(r.choice)}</span></span>`).join('') : '<span class="muted">—</span>'}</div><small>${rows.length}</small></div>`; }).join('')}</div></figure>
  </div>`;
}
export function aggregateCharts(data) {
  const bins = data.lengths || [];
  const max = Math.max(1, ...bins.map(b => b.runs));
  const groups = data.groups || [];
  return `<div class="public-totals"><strong>${data.totalRuns}</strong><span>independent runs</span><strong>${data.totalDecisions}</strong><span>decisions across runs</span></div><p class="small-copy muted">Runs are not people. One person can contribute multiple runs. ${data.withheld ? 'Detailed groups need at least 10 runs.' : ''}</p><div class="charts-grid"><figure class="chart-card"><figcaption>05 / HOW FAR THE RUNS WENT</figcaption><div class="histogram">${bins.map(b => `<div><span>${e(b.label)}</span><i style="width:${b.runs / max * 100}%"></i><strong>${b.runs}</strong></div>`).join('') || '<p>Not enough runs for this chart yet.</p>'}</div><p>Includes ongoing and abandoned runs. This is not a completion rate.</p></figure><figure class="chart-card"><figcaption>06 / INTERVENTION BY THEME</figcaption>${groups.map(g => `<div class="aggregate-bar"><span>${e(FAMILIES.find(f => f.id === g.family)?.name || g.family)} · ${e(g.mode)}</span><div><i style="width:${g.pulled / g.total * 100}%"></i></div><small>${Math.round(g.pulled / g.total * 100)}% · ${g.runs} runs</small></div>`).join('') || '<p>No theme has enough runs to display yet.</p>'}</figure></div><p class="small-copy muted">Snapshot: ${e(data.generatedAt || 'live')}. Percentages count decisions, so long runs contribute more. No raw run IDs are public.</p>`;
}
